### ISSUE TITLE
Text mode firmware scrolling

### ISSUE THREAD

**Issue by mattuna15** [jamesbowman/gd3x-dazzler#2]
I've started using the Textmode firmware to connect to a 68k design I'm using. It works fine until it reaches the bottom of the screen. The scrolling seems to just clear the screen and after that no characters are displayed. I can reset it by sending the ANSI codes for screen mode. 

Is this the code which looks after scrolling?

```
: down1
    1 cy +!
    cy @ t.H 1- = if
        yo @ 1+ hmod yo !
        -1 cy +!
        0 t.W lineclr
        cmd_memcpy
        $3020d8. >gd
        yo @ 4 * t.scr + w>gd
        4 w>gd
    then
;
```

**Comment by jamesbowman** [comment]
Yes that code is called when the cursor has to move down one line. This happens when either ascii code 0x0a is received or the cursor moves right when it's at the right-hand edge of the screen.

What is does is:

- increment the cy ("cursor y") variable
- if cy  reaches the screen height limit (t.H), then...
- increment yo ("y offset"), modulo the screen height, and decrement cy
- clear the current line
- copies the scroll offset from the scroll offset table

So this last step seems to be the one that isn't working.
I'm looking at the regression tests for this in the simulator now.

**Comment by jamesbowman** [comment]
OK, just found it.

The bug was introduced in when py-bteve switched the units of VertexTranslateY() from 1/16 pixel to pixels.

The textmode code wasn't updated, so all scroll offsets are 16 times too large. Chaos results.

Fixed now, will attach a textmode binary image.

**Comment by mattuna15** [comment]
Spot on! Thanks..
![2021-02-03 15 31 04](https://user-images.githubusercontent.com/16086727/106769474-ecac9d00-6634-11eb-8915-e4eb66f2d445.jpg)
